services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"  # Expose the React app on port 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Expose the backend API on port 5000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=vehicles_db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vehicles_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL on port 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
